# Generated by Django 5.1.6 on 2025-03-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_cedula_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
