# Generated by Django 5.1.6 on 2025-03-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
