# Generated by Django 5.1.6 on 2025-04-26 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0008_vehiculo'),
        ('usuarios', '0006_empresa_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='vehiculo_asignado',
            field=models.ForeignKey(blank=True, help_text='Vehículo asignado a este usuario (solo si es conductor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_asignado', to='transporte.vehiculo', verbose_name='Vehículo Asignado'),
        ),
    ]
