# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations

# --- IMPORTANTE: Lista EXACTA de tus roles ---
# Copia esto desde tu models.py si es diferente
ROLES = [
    ('conductor', 'Conductor'),
    ('cliente', 'Cliente'),
    ('jefe_inventario', 'Jefe de Inventario'),
    ('jefe_empresa', 'Jefe de Empresa'),
    ('admin', 'Admin'),
]
# --- FIN ROLES ---

def create_roles(apps, schema_editor):
    """Crea los objetos Rol en la base de datos."""
    Rol = apps.get_model('usuarios', 'Rol') # Obtiene el modelo Rol histórico
    db_alias = schema_editor.connection.alias
    print("\nCreando roles iniciales...") # Mensaje útil para los logs
    for role_key, role_name in ROLES:
        try:
            # Intenta obtener o crear el rol
            obj, created = Rol.objects.using(db_alias).update_or_create(
                nombre=role_key,
                defaults={'nombre': role_key} # Asegura que el nombre sea el correcto
            )
            if created:
                print(f"  - Rol '{role_name}' ({role_key}) creado.")
            else:
                print(f"  - Rol '{role_name}' ({role_key}) ya existía.")
        except Exception as e:
            print(f"  - ERROR creando rol '{role_name}': {e}")


def delete_roles(apps, schema_editor):
    """Opcional: Código para borrar los roles si se revierte la migración."""
    Rol = apps.get_model('usuarios', 'Rol')
    db_alias = schema_editor.connection.alias
    role_keys = [key for key, name in ROLES]
    print(f"\nEliminando roles: {role_keys}")
    Rol.objects.using(db_alias).filter(nombre__in=role_keys).delete()


class Migration(migrations.Migration):

    # Asegúrate que la dependencia sea la migración ANTERIOR de la app 'usuarios'
    dependencies = [
        ('usuarios', '0007_usuario_vehiculo_asignado'), # <-- CAMBIA ESTO al nombre de tu última migración en 'usuarios'
    ]

    operations = [
        # Ejecuta la función create_roles al aplicar la migración
        migrations.RunPython(create_roles, reverse_code=delete_roles),
    ]