# Generated by Django 5.1.6 on 2025-04-01 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaje', '0001_initial'),
        ('usuarios', '0006_empresa_usuario_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AddField(
            model_name='inventario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='usuarios.empresa', verbose_name='Empresa Propietaria'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'ubicacion', 'empresa')},
        ),
    ]
