# Generated by Django 5.1.6 on 2025-04-07 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaje', '0002_alter_inventario_options_inventario_empresa_and_more'),
        ('usuarios', '0006_empresa_usuario_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('CREACION', 'Creación Inicial'), ('ACTUALIZACION', 'Actualización Cantidad'), ('ELIMINACION', 'Eliminación Registro'), ('AJUSTE_POS', 'Ajuste Positivo'), ('AJUSTE_NEG', 'Ajuste Negativo')], max_length=15)),
                ('cantidad_anterior', models.IntegerField(blank=True, null=True)),
                ('cantidad_nueva', models.IntegerField(blank=True, null=True)),
                ('cantidad_cambio', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo/Descripción Adicional')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empresa', verbose_name='Empresa Cliente')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='bodegaje.inventario')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodegaje.producto')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodegaje.ubicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Historial de Inventario',
                'ordering': ['-timestamp'],
            },
        ),
    ]
