# Generated by Django 5.1.6 on 2025-04-19 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaje', '0003_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha Creación Registro'),
        ),
    ]
