# Generated by Django 5.1.6 on 2025-04-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaje', '0004_inventario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Movimiento/Log', 'verbose_name_plural': 'Historial General Bodegaje'},
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad_cambio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del Cambio / Motivo'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('CREACION', 'Creación Inicial Inventario'), ('ACTUALIZACION', 'Actualización Cantidad Inventario'), ('ELIMINACION', 'Eliminación Registro Inventario'), ('AJUSTE_POS', 'Ajuste Positivo Inventario'), ('AJUSTE_NEG', 'Ajuste Negativo Inventario'), ('PROD_CREADO', 'Producto Creado'), ('PROD_MODIFICADO', 'Producto Modificado'), ('PROD_ELIMINADO', 'Producto Eliminado'), ('UBI_CREADA', 'Ubicación Creada'), ('UBI_MODIFICADA', 'Ubicación Modificada'), ('UBI_ELIMINADA', 'Ubicación Eliminada')], max_length=15),
        ),
    ]
