# Generated by Django 5.1.6 on 2025-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidotransporte',
            name='hora_entrega_programada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Entrega Programada (Opcional)'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='hora_recogida_programada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Recogida Programada'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='tiempo_bodegaje_estimado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Bodegaje Estimado'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='tipo_servicio',
            field=models.CharField(choices=[('SIMPLE', 'Envío Simple (Punto a Punto)'), ('BODEGAJE_ENTRADA', 'Dejar en Bodega'), ('BODEGAJE_SALIDA', 'Retirar de Bodega')], default='SIMPLE', max_length=20, verbose_name='Tipo de Servicio'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='tipo_vehiculo_requerido',
            field=models.CharField(blank=True, choices=[('MOTO', 'Motocicleta'), ('PEQUENO', 'Vehículo Pequeño (Automóvil)'), ('MEDIANO', 'Vehículo Mediano (Camioneta/SUV)'), ('GRANDE', 'Vehículo Grande (Furgón/Camión pequeño)')], max_length=50, null=True, verbose_name='Tipo de Vehículo Requerido'),
        ),
    ]
