# Generated by Django 5.1.6 on 2025-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_pedidotransporte_hora_entrega_programada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidotransporte',
            name='dimensiones_contenido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dimensiones/Tamaño Contenido'),
        ),
    ]
