# Generated by Django 5.1.6 on 2025-04-07 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaje', '0003_movimientoinventario'),
        ('transporte', '0003_pedidotransporte_dimensiones_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad a Retirar/Mover')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='transporte.pedidotransporte', verbose_name='Pedido Asociado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodegaje.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
