# Generated by Django 5.1.6 on 2025-04-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_itempedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item de Pedido (Solo Retiro Bodega)', 'verbose_name_plural': 'Items de Pedido (Solo Retiro Bodega)'},
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='distancia_estimada_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Distancia Estimada (Km) (Pasajeros por Distancia)'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='duracion_estimada_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Duración Estimada (H) (Pasajeros por Tiempo)'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='numero_pasajeros',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Pasajeros'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='tipo_tarifa_pasajero',
            field=models.CharField(blank=True, choices=[('TIEMPO', 'Por Tiempo'), ('DISTANCIA', 'Por Distancia')], max_length=10, null=True, verbose_name='Tipo Tarifa (Solo Pasajeros)'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción/Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='destino',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='dimensiones_contenido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dimensiones/Tamaño (Solo Mercancía)'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Fin Real'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Inicio Real'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='hora_entrega_programada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Fin/Entrega Programada'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='hora_recogida_programada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Inicio/Recogida Programada'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='origen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='tiempo_bodegaje_estimado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Bodegaje Estimado (Solo Entrada Bodega)'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='tipo_servicio',
            field=models.CharField(choices=[('SIMPLE', 'Envío Simple (Mercancía Punto a Punto)'), ('BODEGAJE_ENTRADA', 'Dejar Mercancía en Bodega'), ('BODEGAJE_SALIDA', 'Retirar Mercancía de Bodega'), ('PASAJEROS', 'Transporte de Pasajeros'), ('RENTA_VEHICULO', 'Renta Vehículo con Conductor')], default='SIMPLE', max_length=20, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='pedidotransporte',
            name='tipo_vehiculo_requerido',
            field=models.CharField(blank=True, choices=[('MOTO', 'Motocicleta'), ('PEQUENO', 'Vehículo Pequeño (Automóvil)'), ('MEDIANO', 'Vehículo Mediano (Camioneta/SUV)'), ('GRANDE', 'Vehículo Grande (Furgón/Camión pequeño)')], max_length=50, null=True, verbose_name='Tipo de Vehículo Requerido/Rentado'),
        ),
    ]
