# Generated by Django 5.1.6 on 2025-04-17 03:53

import apps.transporte.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0005_alter_itempedido_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidotransporte',
            name='confirmacion_cliente_realizada',
            field=models.BooleanField(default=False, editable=False, verbose_name='Confirmación Cliente OK?'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='fotos_fin_completas',
            field=models.BooleanField(default=False, editable=False, verbose_name='Fotos Fin OK?'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='fotos_inicio_completas',
            field=models.BooleanField(default=False, editable=False, verbose_name='Fotos Inicio OK?'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='requiere_confirmacion_cliente',
            field=models.BooleanField(default=True, verbose_name='¿Requiere Confirmación Cliente (QR/Firma)?'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='requiere_fotos_fin',
            field=models.BooleanField(default=True, verbose_name='¿Requiere Fotos al Finalizar?'),
        ),
        migrations.AddField(
            model_name='pedidotransporte',
            name='requiere_fotos_inicio',
            field=models.BooleanField(default=True, verbose_name='¿Requiere Fotos al Iniciar?'),
        ),
        migrations.CreateModel(
            name='ConfirmacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_receptor', models.CharField(max_length=255, verbose_name='Nombre de quien recibe')),
                ('cedula_receptor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula/ID de quien recibe (Opcional)')),
                ('firma_imagen_base64', models.TextField(blank=True, null=True, verbose_name='Firma (Data URL Base64)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del Cliente')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion_cliente', to='transporte.pedidotransporte', verbose_name='Pedido Asociado')),
            ],
            options={
                'verbose_name': 'Confirmación del Cliente',
                'verbose_name_plural': 'Confirmaciones de Clientes',
            },
        ),
        migrations.CreateModel(
            name='PruebaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('INICIO', 'Inicio Viaje'), ('FIN', 'Fin Viaje')], max_length=10, verbose_name='Etapa del Viaje')),
                ('foto', models.ImageField(upload_to=apps.transporte.models.prueba_entrega_upload_path, verbose_name='Archivo de Foto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_entrega', to='transporte.pedidotransporte', verbose_name='Pedido Asociado')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Prueba de Entrega/Servicio',
                'verbose_name_plural': 'Pruebas de Entrega/Servicio',
                'ordering': ['pedido', 'etapa', 'timestamp'],
            },
        ),
    ]
