# Generated by Django 5.1.6 on 2025-04-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0006_pedidotransporte_confirmacion_cliente_realizada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pruebaentrega',
            options={'ordering': ['pedido', 'timestamp'], 'verbose_name': 'Prueba de Entrega/Servicio', 'verbose_name_plural': 'Pruebas de Entrega/Servicio'},
        ),
        migrations.AddField(
            model_name='pruebaentrega',
            name='tipo_foto',
            field=models.CharField(choices=[('INICIO_GEN', 'Inicio - General'), ('FIN_MERC', 'Fin - Mercancía'), ('FIN_REC', 'Fin - Receptor'), ('FIN_GEN', 'Fin - General')], default='INICIO_GEN', max_length=10, verbose_name='Tipo de Foto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pruebaentrega',
            name='etapa',
            field=models.CharField(choices=[('INICIO', 'Inicio Viaje'), ('FIN', 'Fin Viaje')], editable=False, max_length=10, verbose_name='Etapa del Viaje'),
        ),
    ]
