# Generated by Django 5.1.6 on 2025-04-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0007_alter_pruebaentrega_options_pruebaentrega_tipo_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa única del vehículo (Ej: AAA123)', max_length=10, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('MOTO', 'Motocicleta'), ('PEQUENO', 'Vehículo Pequeño (Automóvil)'), ('MEDIANO', 'Vehículo Mediano (Camioneta/SUV)'), ('GRANDE', 'Vehículo Grande (Furgón/Camión pequeño)')], max_length=50, verbose_name='Tipo de Vehículo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo/Línea')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el vehículo está disponible para ser asignado.', verbose_name='¿Vehículo activo?')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
    ]
