# Generated by Django 5.1.6 on 2025-04-27 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0009_tipovehiculo_alter_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='transporte.tipovehiculo', verbose_name='Tipo de Vehículo'),
        ),
    ]
